"""remove isbn from book model

Revision ID: 596dec86f3bb
Revises: 9b8e96920aae
Create Date: 2026-01-02 14:13:20.379856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596dec86f3bb'
down_revision: Union[str, Sequence[str], None] = '9b8e96920aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_isbn_key'), 'books', type_='unique')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('books_isbn_key'), 'books', ['isbn'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
