"""add version column for optimistic locking

Revision ID: 5f435fe3da4e
Revises: 8b98c7bb891c
Create Date: 2026-01-05 02:17:18.014012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f435fe3da4e'
down_revision: Union[str, Sequence[str], None] = '8b98c7bb891c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'version')
    # ### end Alembic commands ###
