"""add book_copies table and update loans

Revision ID: 6edd809911de
Revises: cc018f9ae89c
Create Date: 2026-01-05 22:40:42.897360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edd809911de'
down_revision: Union[str, Sequence[str], None] = 'cc018f9ae89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_book_title_author', 'books', ['title', 'author'])
    op.add_column('loans', sa.Column('copy_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('uq_active_loan_per_book'), table_name='loans', postgresql_where='(returned_at IS NULL)')
    op.create_index('uq_active_loan_per_copy', 'loans', ['copy_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_constraint(op.f('loans_book_id_fkey'), 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'book_copies', ['copy_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('loans', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key(op.f('loans_book_id_fkey'), 'loans', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('uq_active_loan_per_copy', table_name='loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.create_index(op.f('uq_active_loan_per_book'), 'loans', ['book_id'], unique=True, postgresql_where='(returned_at IS NULL)')
    op.drop_column('loans', 'copy_id')
    op.drop_constraint('uq_book_title_author', 'books', type_='unique')
    op.drop_table('book_copies')
    # ### end Alembic commands ###
