"""add title and active loan index

Revision ID: 83962b1e9b4f
Revises: e085756f0442
Create Date: 2025-12-30 11:20:38.916216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83962b1e9b4f'
down_revision: Union[str, Sequence[str], None] = 'e085756f0442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_book_title', 'books', ['title'], unique=False)
    op.create_index('idx_loan_active_due', 'loans', ['due_to', 'id'], unique=False, postgresql_where=sa.text('returned_at IS NULL'))
    op.create_index('uq_active_loan_per_book', 'loans', ['book_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_loan_per_book', table_name='loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_index('idx_loan_active_due', table_name='loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_index('ix_book_title', table_name='books')
    # ### end Alembic commands ###
