"""add unique constraint on book title and author

Revision ID: 8b98c7bb891c
Revises: 596dec86f3bb
Create Date: 2026-01-04 21:30:32.941644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b98c7bb891c'
down_revision: Union[str, Sequence[str], None] = '596dec86f3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_book_title_author', 'books', ['title', 'author'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_book_title_author', 'books', type_='unique')
    # ### end Alembic commands ###
