"""remove unique constraint on book title and author

Revision ID: cc018f9ae89c
Revises: 5f435fe3da4e
Create Date: 2026-01-05 20:47:11.914900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc018f9ae89c'
down_revision: Union[str, Sequence[str], None] = '5f435fe3da4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_book_title_author'), 'books', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_book_title_author'), 'books', ['title', 'author'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
