"""use Integer for fine_cents, DateTime for dates

Revision ID: e085756f0442
Revises: 22019dba9deb
Create Date: 2025-12-30 11:13:17.751281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e085756f0442'
down_revision: Union[str, Sequence[str], None] = '22019dba9deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('due_to', sa.DateTime(timezone=True), nullable=False))
    op.add_column('loans', sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('loans', sa.Column('loaned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('loans', sa.Column('fine_cents', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('loans_book_id_fkey'), 'loans', type_='foreignkey')
    op.drop_constraint(op.f('loans_user_id_fkey'), 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'loans', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('loans', 'return_date')
    op.drop_column('loans', 'due_date')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'loan_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('loan_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('loans', sa.Column('fine_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('loans', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('loans', sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key(op.f('loans_user_id_fkey'), 'loans', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('loans_book_id_fkey'), 'loans', 'books', ['book_id'], ['id'])
    op.drop_column('loans', 'fine_cents')
    op.drop_column('loans', 'loaned_at')
    op.drop_column('loans', 'returned_at')
    op.drop_column('loans', 'due_to')
    # ### end Alembic commands ###
